version: "3.8"

services:
  lumigo:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: "stephC/lumigo:${VERSION}"
    ports:
      - "${HOST_PORT}:7860"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      MONGODB_URI: "${MONGODB_URI}"
      MONGODB_NAME: "${MONGODB_NAME}"
      COLLECTION: "${COLLECTION}"
      INDEX_NAME: "${INDEX_NAME}"
      DEVICE: "${DEVICE}"
      PROJECT_ID: "${PROJECT_ID}"
      LOCATION: "${LOCATION}"
      GOOGLE_srcLICATION_CREDENTIALS: "/src/credentials.json"

    volumes:
      - ./credentials.json:/src/credentials.json:ro

    stdin_open: true
    tty: true
    restart: unless-stopped
